### ISSUE TITLE
Couple Questions

### ISSUE THREAD

**Issue by Eeveelution** [whowechina/aic_pico#2]
First of all, you mention that the PN5180 also supports older e-Amusement cards, does that mean it supports all possible e-Amusement cards? or that it only supports the older ones?

Also is the keypad necessary to read cards that have PINs/Passwords set? Or can you just build one of those without a keypad and enter it some other way?

**Comment by whowechina** [comment]
"Also" means "Also", not "only". Newer e-amusement cards are FeliCa cards.

Keypad is just another small numpad (regular keyboard).

**Comment by Eeveelution** [comment]
got it, thank you for answering! Yeah I assumed that's what the 'also' meant but wanted to be 1000% sure.
